import type { Airport, FlightOffer } from "./types";

export const airports: Airport[] = [
  { code: "CLE", city: "Cleveland", name: "Cleveland Hopkins", region: "Ohio" },
  { code: "LAX", city: "Los Angeles", name: "Los Angeles International", region: "California" },
  { code: "JFK", city: "New York", name: "John F. Kennedy", region: "New York" },
  { code: "SFO", city: "San Francisco", name: "San Francisco International", region: "California" },
  { code: "ORD", city: "Chicago", name: "O'Hare International", region: "Illinois" },
  { code: "ATL", city: "Atlanta", name: "Hartsfield-Jackson", region: "Georgia" },
  { code: "MIA", city: "Miami", name: "Miami International", region: "Florida" },
  { code: "SEA", city: "Seattle", name: "Seattle-Tacoma", region: "Washington" },
];

export const priceCalendar = [
  { date: "May 18", amount: 268, tone: "good" },
  { date: "May 19", amount: 244, tone: "best" },
  { date: "May 20", amount: 303, tone: "ok" },
  { date: "May 21", amount: 286, tone: "selected" },
  { date: "May 22", amount: 318, tone: "ok" },
  { date: "May 23", amount: 351, tone: "high" },
  { date: "May 24", amount: 299, tone: "ok" },
];

export const flightOffers: FlightOffer[] = [
  {
    id: "fc-ua-872",
    airline: "United",
    airlineCode: "UA",
    accent: "#1f6feb",
    price: 286,
    previousPrice: 329,
    currency: "USD",
    departTime: "7:05 AM",
    arriveTime: "10:02 AM",
    durationMinutes: 357,
    stops: 0,
    stopLabel: "Nonstop",
    route: "CLE - LAX",
    confidence: 92,
    baggage: "Carry-on included",
    carbon: "11% below route avg",
    fareType: "Economy standard",
    changePolicy: "Free same-day standby, change fees vary by fare",
    tags: ["Best pick", "Early arrival", "Nonstop"],
    segments: [
      { from: "CLE", to: "LAX", depart: "7:05 AM", arrive: "10:02 AM", flight: "UA 872" },
      { from: "LAX", to: "CLE", depart: "2:15 PM", arrive: "9:34 PM", flight: "UA 1184" },
    ],
  },
  {
    id: "fc-dl-449",
    airline: "Delta",
    airlineCode: "DL",
    accent: "#c8102e",
    price: 244,
    previousPrice: 318,
    currency: "USD",
    departTime: "12:22 PM",
    arriveTime: "5:48 PM",
    durationMinutes: 506,
    stops: 1,
    stopLabel: "1 stop ATL",
    route: "CLE - ATL - LAX",
    confidence: 87,
    baggage: "Personal item included",
    carbon: "Typical for route",
    fareType: "Main cabin",
    changePolicy: "No change fee on most domestic main cabin fares",
    tags: ["Cheapest", "Longer layover"],
    segments: [
      { from: "CLE", to: "ATL", depart: "12:22 PM", arrive: "2:09 PM", flight: "DL 2141" },
      { from: "ATL", to: "LAX", depart: "3:05 PM", arrive: "5:48 PM", flight: "DL 503" },
    ],
  },
  {
    id: "fc-aa-1208",
    airline: "American",
    airlineCode: "AA",
    accent: "#d71920",
    price: 302,
    previousPrice: 302,
    currency: "USD",
    departTime: "9:45 AM",
    arriveTime: "1:31 PM",
    durationMinutes: 406,
    stops: 1,
    stopLabel: "1 stop DFW",
    route: "CLE - DFW - LAX",
    confidence: 79,
    baggage: "Carry-on included",
    carbon: "7% above route avg",
    fareType: "Main cabin",
    changePolicy: "Trip credit applies for eligible cancellations",
    tags: ["Good timing", "Short connection"],
    segments: [
      { from: "CLE", to: "DFW", depart: "9:45 AM", arrive: "11:38 AM", flight: "AA 1208" },
      { from: "DFW", to: "LAX", depart: "12:20 PM", arrive: "1:31 PM", flight: "AA 1618" },
    ],
  },
  {
    id: "fc-sw-512",
    airline: "Southwest",
    airlineCode: "WN",
    accent: "#ffbf27",
    price: 276,
    previousPrice: 311,
    currency: "USD",
    departTime: "6:10 AM",
    arriveTime: "11:20 AM",
    durationMinutes: 430,
    stops: 1,
    stopLabel: "1 stop MDW",
    route: "CLE - MDW - LAX",
    confidence: 83,
    baggage: "Two checked bags included",
    carbon: "5% below route avg",
    fareType: "Wanna Get Away",
    changePolicy: "No airline change fees, fare difference may apply",
    tags: ["Bags included", "Flexible"],
    segments: [
      { from: "CLE", to: "MDW", depart: "6:10 AM", arrive: "6:25 AM", flight: "WN 512" },
      { from: "MDW", to: "LAX", depart: "7:40 AM", arrive: "11:20 AM", flight: "WN 2904" },
    ],
  },
];

export const savedTrips = [
  { route: "CLE to LAX", date: "May 21 - May 30", status: "Watching", price: "$286" },
  { route: "CLE to SFO", date: "June 12 - June 18", status: "Price drop", price: "$312" },
];
